const db = require("../db/connection");
const Equipment = require("../models/equipment");

db.on("error", console.error.bind(console, "MongoDB connection error:"));

const main = async () => {
  const equipments = [
    {
      name: 'Dish Washer 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/dish-washer.jpg',
      category: 'dish washer',
      money: 15,
      energy: 20,
      trees: 15,
      water: 8,
    },
    {
      name: 'Light Bulb 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/light-bulb1.jpeg',
      category: 'light bulb',
      money: 5,
      energy: 10,
      trees: 0,
      water: 0,
    },
    {
      name: 'Light Bulb 2',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/light-bulb2.jpeg',
      category: 'light bulb',
      money: 5,
      energy: 10,
      trees: 0,
      water: 0,
    },
        {
      name: 'Light Bulb 3',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/light-bulb3.jpeg',
      category: 'light bulb',
      money: 5,
      energy: 10,
      trees: 0,
      water: 0,
    },
    {
      name: 'Microwave 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave01.jpeg',
      category: 'microwave',
      money: 5,
      energy: 100,
      trees: 15,
      water: 0,
    },
    {
      name: 'Microwave 2',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave02.jpeg',
      category: 'microwave',
      money: 5,
      energy: 100,
      trees: 15,
      water: 0,
    },
    {
      name: 'Microwave 3',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave03.jpeg',
      category: 'microwave',
      money: 5,
      energy: 100,
      trees: 15,
      water: 0,
    },
    {
      name: 'Microwave 4',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave04.jpeg',
      category: 'microwave',
      money: 5,
      energy: 100,
      trees: 15,
      water: 0,
    },
    {
      name: 'Microwave 5',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave05.jpeg',
      category: 'microwave',
      money: 7,
      energy: 120,
      trees: 6,
      water: 0,
    },
    {
      name: 'Microwave 6',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave06.jpeg',
      category: 'microwave',
      money: 3,
      energy: 80,
      trees: 2,
      water: 0,
    },
    {
      name: 'Microwave 7',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave07.jpeg',
      category: 'microwave',
      money: 4,
      energy: 60,
      trees: 1,
      water: 0,
    },
    {
      name: 'Microwave 8',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave08.jpeg',
      category: 'microwave',
      money: 7,
      energy: 30,
      trees: 4,
      water: 0,
    },
    {
      name: 'Microwave 9',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave09.jpeg',
      category: 'microwave',
      money: 16,
      energy: 75,
      trees: 4,
      water: 0,
    },
    {
      name: 'Microwave 10',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/microwave10.jpeg',
      category: 'microwave',
      money: 11,
      energy: 40,
      trees: 3,
      water: 0,
    },
    {
      name: 'Power Meter',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/plug-timer.jpg',
      category: 'other',
      money: 25,
      energy: 200,
      trees: 0,
      water: 0,
    },
    {
      name: 'Refrigerator 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/refrigerator.jpg',
      category: 'refrigerator',
      money: 40,
      energy: 150,
      trees: 0,
      water: 4,
    },
    {
      name: 'Refrigerator 2',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/refrigerator1.jpg',
      category: 'refrigerator',
      money: 45,
      energy: 125,
      trees: 0,
      water: 5,
    },
    {
      name: 'Shower Head 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/shower-head1.png',
      category: 'shower head',
      money: 13,
      energy: 0,
      trees: 0,
      water: 31,
    },
    {
      name: 'Solar Panel 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/solar-panel1.jpeg',
      category: 'solar panel',
      money: 78,
      energy: 1000,
      trees: 7,
      water: 0,
    },
    {
      name: 'Washine Machine 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/washing-machine1.jpg',
      category: 'washing machine',
      money: 47,
      energy: 300,
      trees: 15,
      water: 42,
    },
    {
      name: 'Washing Machine 2',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/washing-machine2.jpg',
      category: 'washing machine',
      money: 62,
      energy: 275,
      trees: 3,
      water: 36,
    },
    {
      name: 'Window 1',
      imgURL: 'https://raw.githubusercontent.com/suttondemlong/green-house/develop/EquipmentAssets/window.png',
      category: 'other',
      money: 21,
      energy: 73,
      trees: 7,
      water: 0,
    },
  ]
  await Equipment.insertMany(equipments);
  console.log("Created an equipment!");
};
const run = async () => {
  await main();
  db.close();
};

run();